version: '3'
services:
  dashboard_api:
    build:
      context: .
      dockerfile: api/dashboard/Dockerfile
    ports:
      - "${DASHBOARD_API_PORT}:5002"
    volumes:
      - ./api/dashboard:/app/api/dashboard
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./workspace:/app/workspace
      - snapshots_volume:/app/snapshots
    env_file:
      - .env
    environment:
      - FLASK_APP=/app/api/dashboard/app.py
      - DASHBOARD_URL=http://dashboard_frontend
      - EVIDENTLY_URL=http://evidently_ui:8000
    depends_on:
      - mongodb

  dashboard_frontend:
    build:
      context: .
      dockerfile: frontend/dashboard/Dockerfile
    ports:
      - "${DASHBOARD_FRONTEND_PORT}:80"
    environment:
      - REACT_APP_DASHBOARD_API_URL=http://dashboard_api:5002


  evidently_ui:
    build:
      context: .
      dockerfile: Dockerfile.evidently
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace
      - snapshots_volume:/app/snapshots
    command: ["evidently", "ui", "--host", "0.0.0.0"]
    env_file:
      - .env

  data_ingestion_api:
    build:
      context: .
      dockerfile: api/ingestion/Dockerfile
    ports:
    - "${INGESTION_API_PORT}:5001"
    volumes:
      - ./api/ingestion:/app/api/ingestion
      - ./src:/app/src
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - FLASK_APP=/app/api/ingestion/app.py
      - INGESTION_FRONTEND_URL=http://ingestion_frontend
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb

  ingestion_frontend:
    build:
      context: .
      dockerfile: frontend/ingestion/Dockerfile
    ports:
      - "${INGESTION_FRONTEND_PORT}:80"
    environment:
      - REACT_APP_INGESTION_API_URL=http://data_ingestion_api:5001

  mongodb:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

volumes:
  mongodb_data:
  snapshots_volume:

networks:
  default:
    name: monitoring-network