services:
  dashboard_api:
    build:
      context: .
      dockerfile: api/dashboard/Dockerfile
    volumes:
      - ./snapshots:/app/snapshots
      - ./workspace:/app/workspace
    env_file:
      - .env
    environment:
      - DASHBOARD_URL=http://localhost:3000
      - EVIDENTLY_URL=http://localhost:8000
      - DASHBOARD_FRONTEND_URL=http://localhost:3000
    ports:
      - "${DASHBOARD_API_PORT:-5002}:5002"
    depends_on:
      - mongodb

  dashboard_frontend:
    build:
      context: .
      dockerfile: frontend/dashboard/Dockerfile
    ports:
      - "${DASHBOARD_FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_DASHBOARD_API_URL=http://localhost:5002

  evidently_ui:
    build:
      context: .
      dockerfile: Dockerfile.evidently
    ports:
      - "8000:8000"
    volumes:
      - ./snapshots:/app/snapshots
      - ./workspace:/app/workspace
    command: ["evidently", "ui", "--host", "0.0.0.0"]
    env_file:
      - .env

  data_ingestion_api:
    build:
      context: .
      dockerfile: api/ingestion/Dockerfile
    volumes:
      - ./snapshots:/app/snapshots
    env_file:
      - .env
    environment:
      - INGESTION_FRONTEND_URL=http://ingestion_frontend:3001
      - INGESTION_API_PORT=${INGESTION_API_PORT:-5001}
    ports:
      - "${INGESTION_API_PORT:-5001}:5001"
    depends_on:
      - mongodb

  ingestion_frontend:
    build:
      context: .
      dockerfile: frontend/ingestion/Dockerfile
    ports:
      - "${INGESTION_FRONTEND_PORT:-3001}:3001"
    environment:
      - REACT_APP_INGESTION_API_URL=http://localhost:5001

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  
  prefect_agent:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    volumes:
      - ./snapshots:/app/snapshots
      - ./workspace:/app/workspace
      - ./data:/app/data
    environment:
      - PREFECT_API_URL=http://host.docker.internal:4200/api
      - MONGO_URI=${MONGO_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "chmod -R 777 /app/snapshots /app/workspace && /app/flow/start.sh"

volumes:
  mongodb_data:
  snapshots_volume:

networks:
  default:
    name: monitoring-network