FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/workspace

EXPOSE 8000

CMD ["evidently", "ui", "--workspace", "/app/workspace", "--host", "0.0.0.0"]
