version: '3'
services:
  dashboard_api:
    build:
      context: .
      dockerfile: api/dashboard/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./api/dashboard:/app/api/dashboard
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./workspace:/app/workspace
    env_file:
      - .env
    environment:
      - FLASK_APP=/app/api/dashboard/app.py
    depends_on:
      - mongodb

  dashboard_frontend:
    build:
      context: .
      dockerfile: frontend/dashboard/Dockerfile
    ports:
      - "${DASHBOARD_FRONTEND_PORT}:3000"
    env_file:
      - .env

  evidently_ui:
    build:
      context: .
      dockerfile: Dockerfile.evidently
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace
    command: ["evidently", "ui", "--host", "0.0.0.0"]
    env_file:
      - .env

  data_ingestion_api:
    build:
      context: .
      dockerfile: api/ingestion/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./api/ingestion:/app/api/ingestion
      - ./src:/app/src
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - FLASK_APP=/app/api/ingestion/app.py
    depends_on:
      - mongodb

  ingestion_frontend:
    build:
      context: .
      dockerfile: frontend/ingestion/Dockerfile
    ports:
      - "${INGESTION_FRONTEND_PORT}:3001"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27016"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    name: monitoring-network